package net.js.jsmenu.block;

import net.js.jsmenu.JSMenu;
import net.js.jsmenu.block.custom.RadioactiveBlock;
import net.js.jsmenu.block.custom.SuperRadioactiveBlock;
import net.js.jsmenu.item.ModItems;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.registries.DeferredRegister;

import java.util.function.Supplier;

public class ModBlocks {
    public static final DeferredRegister.Blocks BLOCKS =
            DeferredRegister.createBlocks(JSMenu.MOD_ID);
    public static final DeferredBlock<Block> HYDROGEN_ORE = registerBlock("hydrogen_ore", () -> new Block(BlockBehaviour.Properties.of().strength(0.75f).air()));
    public static final DeferredBlock<Block> LITHIUM_ORE = registerBlock("lithium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(1.175f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> BERYLLIUM_ORE = registerBlock("beryllium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(1.2f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> BORON_ORE = registerBlock("boron_ore", () -> new Block(BlockBehaviour.Properties.of().strength(2f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> CARBON_ORE = registerBlock("carbon_ore", () -> new Block(BlockBehaviour.Properties.of().strength(2.3f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> NITROGEN_ORE = registerBlock("nitrogen_ore", () -> new Block(BlockBehaviour.Properties.of().strength(2.335f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> OXYGEN_ORE = registerBlock("oxygen_ore", () -> new Block(BlockBehaviour.Properties.of().strength(2.35f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> FLUORINE_ORE = registerBlock("fluorine_ore", () -> new Block(BlockBehaviour.Properties.of().strength(2.37f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> NEON_ORE = registerBlock("neon_ore", () -> new Block(BlockBehaviour.Properties.of().strength(1.13f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> SODIUM_ORE = registerBlock("sodium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(1.95f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> MAGNESIUM_ORE = registerBlock("magnesium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(2.04f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> ALUMINUM_ORE = registerBlock("aluminum_ore", () -> new Block(BlockBehaviour.Properties.of().strength(2.65f).requiresCorrectToolForDrops().sound(SoundType.DEEPSLATE)));
    public static final DeferredBlock<Block> SILICON_ORE = registerBlock("silicon_ore", () -> new Block(BlockBehaviour.Properties.of().strength(2.65f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> PHOSPHORUS_ORE = registerBlock("phosphorus_ore", () -> new Block(BlockBehaviour.Properties.of().strength(2.65f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> SULFUR_ORE = registerBlock("sulfur_ore", () -> new Block(BlockBehaviour.Properties.of().strength(2.65f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> CHLORINE_ORE = registerBlock("chlorine_ore", () -> new Block(BlockBehaviour.Properties.of().strength(2.65f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> ARGON_ORE = registerBlock("argon_ore", () -> new Block(BlockBehaviour.Properties.of().strength(2.65f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> POTASSIUM_ORE = registerBlock("potassium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(2.7f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> CALCIUM_ORE = registerBlock("calcium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(2.705f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> SCANDIUM_ORE = registerBlock("scandium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(2.75f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> TITANIUM_ORE = registerBlock("titanium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(2.765f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> VANADIUM_ORE = registerBlock("vanadium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(2.9f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> CHROMIUM_ORE = registerBlock("chromium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(3f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> MANGANESE_ORE = registerBlock("manganese_ore", () -> new Block(BlockBehaviour.Properties.of().strength(3f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> COBALT_ORE = registerBlock("cobalt_ore", () -> new Block(BlockBehaviour.Properties.of().strength(3f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> NICKEL_ORE = registerBlock("nickel_ore", () -> new Block(BlockBehaviour.Properties.of().strength(3.15f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> ZINC_ORE = registerBlock("zinc_ore", () -> new Block(BlockBehaviour.Properties.of().strength(3.1505f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> GALLIUM_ORE = registerBlock("gallium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(3.555f).requiresCorrectToolForDrops().sound(SoundType.DEEPSLATE)));
    public static final DeferredBlock<Block> GERMANIUM_ORE = registerBlock("germanium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(3.1565f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> ARSENIC_ORE = registerBlock("arsenic_ore", () -> new Block(BlockBehaviour.Properties.of().strength(3.1575f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> SELENIUM_ORE = registerBlock("selenium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(3.185f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> KRYPTON_ORE = registerBlock("krypton_ore", () -> new Block(BlockBehaviour.Properties.of().strength(3.625f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RUBIDIUM_ORE = registerBlock("rubidium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(3.85f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> STRONTIUM_ORE = registerBlock("strontium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(3.875f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> YTTRIUM_ORE = registerBlock("yttrium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(3.9f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> ZIRCONIUM_ORE = registerBlock("zirconium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(3.9125f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> NIOBIUM_ORE = registerBlock("niobium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(3.92f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> MOLYBDENUM_ORE = registerBlock("molybdenum_ore", () -> new Block(BlockBehaviour.Properties.of().strength(3.925f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> TECHNETIUM_ORE = registerBlock("technetium_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(3.9275f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RUTHENIUM_ORE = registerBlock("ruthenium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(3.93f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RHODIUM_ORE = registerBlock("rhodium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(3.935f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> PALLADIUM_ORE = registerBlock("palladium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(3.9375f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> SILVER_ORE = registerBlock("silver_ore", () -> new Block(BlockBehaviour.Properties.of().strength(3.94f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> CADMIUM_ORE = registerBlock("cadmium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(3.9f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> INDIUM_ORE = registerBlock("indium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(3.975f).requiresCorrectToolForDrops().sound(SoundType.DEEPSLATE)));
    public static final DeferredBlock<Block> TIN_ORE = registerBlock("tin_ore", () -> new Block(BlockBehaviour.Properties.of().strength(4f).requiresCorrectToolForDrops().sound(SoundType.DEEPSLATE)));
    public static final DeferredBlock<Block> ANTIMONY_ORE = registerBlock("antimony_ore", () -> new Block(BlockBehaviour.Properties.of().strength(4.05f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> TELLURIUM_ORE = registerBlock("tellurium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(4.125f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> IODINE_ORE = registerBlock("iodine_ore", () -> new Block(BlockBehaviour.Properties.of().strength(4.2f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> XENON_ORE = registerBlock("xenon_ore", () -> new Block(BlockBehaviour.Properties.of().strength(4.25f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> CAESIUM_ORE = registerBlock("caesium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(4.35f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> BARIUM_ORE = registerBlock("barium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(4.375f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> LANTHANUM_ORE = registerBlock("lanthanum_ore", () -> new Block(BlockBehaviour.Properties.of().strength(4.5f).requiresCorrectToolForDrops().sound(SoundType.NETHERRACK)));
    public static final DeferredBlock<Block> CERIUM_ORE = registerBlock("cerium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(4.52f).requiresCorrectToolForDrops().sound(SoundType.NETHERRACK)));
    public static final DeferredBlock<Block> PRASEODYMIUM_ORE = registerBlock("praseodymium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(4.55f).requiresCorrectToolForDrops().sound(SoundType.NETHERRACK)));
    public static final DeferredBlock<Block> NEODYMIUM_ORE = registerBlock("neodymium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(4.57f).requiresCorrectToolForDrops().sound(SoundType.NETHERRACK)));
    public static final DeferredBlock<Block> PROMETHIUM_ORE = registerBlock("promethium_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(4.59f).requiresCorrectToolForDrops().sound(SoundType.NETHERRACK)));
    public static final DeferredBlock<Block> SAMARIUM_ORE = registerBlock("samarium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(4.6f).requiresCorrectToolForDrops().sound(SoundType.NETHERRACK)));
    public static final DeferredBlock<Block> EUROPIUM_ORE = registerBlock("europium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(4.7f).requiresCorrectToolForDrops().sound(SoundType.NETHERRACK)));
    public static final DeferredBlock<Block> GADOLINIUM_ORE = registerBlock("gadolinium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(4.725f).requiresCorrectToolForDrops().sound(SoundType.NETHERRACK)));
    public static final DeferredBlock<Block> TERBIUM_ORE = registerBlock("terbium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(4.75f).requiresCorrectToolForDrops().sound(SoundType.NETHERRACK)));
    public static final DeferredBlock<Block> DYSPROSIUM_ORE = registerBlock("dysprosium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(4.75725f).requiresCorrectToolForDrops().sound(SoundType.NETHERRACK)));
    public static final DeferredBlock<Block> HOLMIUM_ORE = registerBlock("holmium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(4.8f).requiresCorrectToolForDrops().sound(SoundType.NETHERRACK)));
    public static final DeferredBlock<Block> ERBIUM_ORE = registerBlock("erbium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(4.95f).requiresCorrectToolForDrops().sound(SoundType.NETHERRACK)));
    public static final DeferredBlock<Block> THULIUM_ORE = registerBlock("thulium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(4.951f).requiresCorrectToolForDrops().sound(SoundType.NETHERRACK)));
    public static final DeferredBlock<Block> YTTERBIUM_ORE = registerBlock("ytterbium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(4.96f).requiresCorrectToolForDrops().sound(SoundType.NETHERRACK)));
    public static final DeferredBlock<Block> LUTETIUM_ORE = registerBlock("lutetium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(4.99f).requiresCorrectToolForDrops().sound(SoundType.NETHERRACK)));
    public static final DeferredBlock<Block> HAFNIUM_ORE = registerBlock("hafnium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> TANTALUM_ORE = registerBlock("tantalum_ore", () -> new Block(BlockBehaviour.Properties.of().strength(5.05f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> TUNGSTEN_ORE = registerBlock("tungsten_ore", () -> new Block(BlockBehaviour.Properties.of().strength(5.075f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RHENIUM_ORE = registerBlock("rhenium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(5.1f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> OSMIUM_ORE = registerBlock("osmium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(5.2f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> IRIDIUM_ORE = registerBlock("iridium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(5.25f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> PLATINUM_ORE = registerBlock("platinum_ore", () -> new Block(BlockBehaviour.Properties.of().strength(5.3f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> THALLIUM_ORE = registerBlock("thallium_ore", () -> new Block(BlockBehaviour.Properties.of().strength(5.3575f).requiresCorrectToolForDrops().sound(SoundType.DEEPSLATE)));
    public static final DeferredBlock<Block> LEAD_ORE = registerBlock("lead_ore", () -> new Block(BlockBehaviour.Properties.of().strength(5.5f).requiresCorrectToolForDrops().sound(SoundType.DEEPSLATE)));
    public static final DeferredBlock<Block> BISMUTH_ORE = registerBlock("bismuth_ore", () -> new Block(BlockBehaviour.Properties.of().strength(5.75f).requiresCorrectToolForDrops().sound(SoundType.DEEPSLATE)));
    public static final DeferredBlock<Block> POLONIUM_ORE = registerBlock("polonium_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(5.95f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> ASTATINE_ORE = registerBlock("astatine_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RADON_ORE = registerBlock("radon_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> FRANCIUM_ORE = registerBlock("francium_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RADIUM_ORE = registerBlock("radium_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> ACTINIUM_ORE = registerBlock("actinium_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> THORIUM_ORE = registerBlock("thorium_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> PROTACTINIUM_ORE = registerBlock("protactinium_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> URANIUM_ORE = registerBlock("uranium_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> NEPTUNIUM_ORE = registerBlock("neptunium_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> PLUTONIUM_ORE = registerBlock("plutonium_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> AMERICIUM_ORE = registerBlock("americium_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> CURIUM_ORE = registerBlock("curium_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> BERKELIUM_ORE = registerBlock("berkelium_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> CALIFORNIUM_ORE = registerBlock("californium_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> EINSTEINIUM_ORE = registerBlock("einsteinium_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> FERMIUM_ORE = registerBlock("fermium_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> MENDELEVIUM_ORE = registerBlock("mendelevium_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> NOBELIUM_ORE = registerBlock("nobelium_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> LAWRENCIUM_ORE = registerBlock("lawrencium_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RUTHERFORDIUM_ORE = registerBlock("rutherfordium_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops().sound(SoundType.TUFF)));
    public static final DeferredBlock<Block> DUBNIUM_ORE = registerBlock("dubnium_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops().sound(SoundType.TUFF)));
    public static final DeferredBlock<Block> SEABORGIUM_ORE = registerBlock("seaborgium_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops().sound(SoundType.TUFF)));
    public static final DeferredBlock<Block> BOHRIUM_ORE = registerBlock("bohrium_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops().sound(SoundType.TUFF)));
    public static final DeferredBlock<Block> HASSIUM_ORE = registerBlock("hassium_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops().sound(SoundType.TUFF)));
    public static final DeferredBlock<Block> MEITNERIUM_ORE = registerBlock("meitnerium_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops().sound(SoundType.TUFF)));
    public static final DeferredBlock<Block> DARMSTADTIUM_ORE = registerBlock("darmstadtium_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops().sound(SoundType.TUFF)));
    public static final DeferredBlock<Block> ROENTGENIUM_ORE = registerBlock("roentgenium_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops().sound(SoundType.TUFF)));
    public static final DeferredBlock<Block> COPERNICIUM_ORE = registerBlock("copernicium_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops().sound(SoundType.TUFF)));
    public static final DeferredBlock<Block> NIHONIUM_ORE = registerBlock("nihonium_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops().sound(SoundType.DEEPSLATE)));
    public static final DeferredBlock<Block> FLEROVIUM_ORE = registerBlock("flerovium_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops().sound(SoundType.DEEPSLATE)));
    public static final DeferredBlock<Block> MOSCOVIUM_ORE = registerBlock("moscovium_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops().sound(SoundType.DEEPSLATE)));
    public static final DeferredBlock<Block> LIVERMORIUM_ORE = registerBlock("livermorium_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops().sound(SoundType.DEEPSLATE)));
    public static final DeferredBlock<Block> TENNESSINE_ORE = registerBlock("tennessine_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> OGANESSON_ORE = registerBlock("oganesson_ore", () -> new RadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));

    public static final DeferredBlock<Block> HYDROGEN_BLOCK = registerBlock("hydrogen_block", () -> new Block(BlockBehaviour.Properties.of().strength(.75f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> HELIUM_BLOCK = registerBlock("helium_block", () -> new Block(BlockBehaviour.Properties.of().strength(1.175f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> LITHIUM_BLOCK = registerBlock("lithium_block", () -> new Block(BlockBehaviour.Properties.of().strength(1.2f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> BERYLLIUM_BLOCK = registerBlock("beryllium_block", () -> new Block(BlockBehaviour.Properties.of().strength(2f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> BORON_BLOCK = registerBlock("boron_block", () -> new Block(BlockBehaviour.Properties.of().strength(2.3f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> CARBON_BLOCK = registerBlock("carbon_block", () -> new Block(BlockBehaviour.Properties.of().strength(2.335f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> NITROGEN_BLOCK = registerBlock("nitrogen_block", () -> new Block(BlockBehaviour.Properties.of().strength(2.35f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> OXYGEN_BLOCK = registerBlock("oxygen_block", () -> new Block(BlockBehaviour.Properties.of().strength(2.37f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> FLUORINE_BLOCK = registerBlock("fluorine_block", () -> new Block(BlockBehaviour.Properties.of().strength(1.13f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> NEON_BLOCK = registerBlock("neon_block", () -> new Block(BlockBehaviour.Properties.of().strength(1.95f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> SODIUM_BLOCK = registerBlock("sodium_block", () -> new Block(BlockBehaviour.Properties.of().strength(2.04f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> MAGNESIUM_BLOCK = registerBlock("magnesium_block", () -> new Block(BlockBehaviour.Properties.of().strength(2.65f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> ALUMINUM_BLOCK = registerBlock("aluminum_block", () -> new Block(BlockBehaviour.Properties.of().strength(2.65f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> SILICON_BLOCK = registerBlock("silicon_block", () -> new Block(BlockBehaviour.Properties.of().strength(2.65f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> PHOSPHORUS_BLOCK = registerBlock("phosphorus_block", () -> new Block(BlockBehaviour.Properties.of().strength(2.65f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> SULFUR_BLOCK = registerBlock("sulfur_block", () -> new Block(BlockBehaviour.Properties.of().strength(2.65f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> CHLORINE_BLOCK = registerBlock("chlorine_block", () -> new Block(BlockBehaviour.Properties.of().strength(2.65f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> ARGON_BLOCK = registerBlock("argon_block", () -> new Block(BlockBehaviour.Properties.of().strength(2.7f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> POTASSIUM_BLOCK = registerBlock("potassium_block", () -> new Block(BlockBehaviour.Properties.of().strength(2.705f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> CALCIUM_BLOCK = registerBlock("calcium_block", () -> new Block(BlockBehaviour.Properties.of().strength(2.75f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RAW_SCANDIUM_BLOCK = registerBlock("raw_scandium_block", () -> new Block(BlockBehaviour.Properties.of().strength(2.765f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> SCANDIUM_BLOCK = registerBlock("scandium_block", () -> new Block(BlockBehaviour.Properties.of().strength(2.9f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RAW_TITANIUM_BLOCK = registerBlock("raw_titanium_block", () -> new Block(BlockBehaviour.Properties.of().strength(3f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> TITANIUM_BLOCK = registerBlock("titanium_block", () -> new Block(BlockBehaviour.Properties.of().strength(3f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RAW_VANADIUM_BLOCK = registerBlock("raw_vanadium_block", () -> new Block(BlockBehaviour.Properties.of().strength(3f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> VANADIUM_BLOCK = registerBlock("vanadium_block", () -> new Block(BlockBehaviour.Properties.of().strength(3.15f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RAW_CHROMIUM_BLOCK = registerBlock("raw_chromium_block", () -> new Block(BlockBehaviour.Properties.of().strength(3.1505f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> CHROMIUM_BLOCK = registerBlock("chromium_block", () -> new Block(BlockBehaviour.Properties.of().strength(3.555f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RAW_MANGANESE_BLOCK = registerBlock("raw_manganese_block", () -> new Block(BlockBehaviour.Properties.of().strength(3.1565f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> MANGANESE_BLOCK = registerBlock("manganese_block", () -> new Block(BlockBehaviour.Properties.of().strength(3.1575f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RAW_COBALT_BLOCK = registerBlock("raw_cobalt_block", () -> new Block(BlockBehaviour.Properties.of().strength(3.185f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> COBALT_BLOCK = registerBlock("cobalt_block", () -> new Block(BlockBehaviour.Properties.of().strength(3.625f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RAW_NICKEL_BLOCK = registerBlock("raw_nickel_block", () -> new Block(BlockBehaviour.Properties.of().strength(3.85f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> NICKEL_BLOCK = registerBlock("nickel_block", () -> new Block(BlockBehaviour.Properties.of().strength(3.875f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RAW_ZINC_BLOCK = registerBlock("raw_zinc_block", () -> new Block(BlockBehaviour.Properties.of().strength(3.9f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> ZINC_BLOCK = registerBlock("zinc_block", () -> new Block(BlockBehaviour.Properties.of().strength(3.9125f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> GALLIUM_BLOCK = registerBlock("gallium_block", () -> new Block(BlockBehaviour.Properties.of().strength(3.92f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> GERMANIUM_BLOCK = registerBlock("germanium_block", () -> new Block(BlockBehaviour.Properties.of().strength(3.925f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> ARSENIC_BLOCK = registerBlock("arsenic_block", () -> new Block(BlockBehaviour.Properties.of().strength(3.9275f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> SELENIUM_BLOCK = registerBlock("selenium_block", () -> new Block(BlockBehaviour.Properties.of().strength(3.935f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> KRYPTON_BLOCK = registerBlock("krypton_block", () -> new Block(BlockBehaviour.Properties.of().strength(3.9375f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RUBIDIUM_BLOCK = registerBlock("rubidium_block", () -> new Block(BlockBehaviour.Properties.of().strength(3.94f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> STRONTIUM_BLOCK = registerBlock("strontium_block", () -> new Block(BlockBehaviour.Properties.of().strength(3.9f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RAW_YTTRIUM_BLOCK = registerBlock("raw_yttrium_block", () -> new Block(BlockBehaviour.Properties.of().strength(3.975f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> YTTRIUM_BLOCK = registerBlock("yttrium_block", () -> new Block(BlockBehaviour.Properties.of().strength(4f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RAW_ZIRCONIUM_BLOCK = registerBlock("raw_zirconium_block", () -> new Block(BlockBehaviour.Properties.of().strength(4.05f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> ZIRCONIUM_BLOCK = registerBlock("zirconium_block", () -> new Block(BlockBehaviour.Properties.of().strength(4.125f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RAW_NIOBIUM_BLOCK = registerBlock("raw_niobium_block", () -> new Block(BlockBehaviour.Properties.of().strength(4.2f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> NIOBIUM_BLOCK = registerBlock("niobium_block", () -> new Block(BlockBehaviour.Properties.of().strength(4.25f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RAW_MOLYBDENUM_BLOCK = registerBlock("raw_molybdenum_block", () -> new Block(BlockBehaviour.Properties.of().strength(4.35f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> MOLYBDENUM_BLOCK = registerBlock("molybdenum_block", () -> new Block(BlockBehaviour.Properties.of().strength(4.375f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> TECHNETIUM_BLOCK = registerBlock("technetium_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(4.475f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RAW_RUTHENIUM_BLOCK = registerBlock("raw_ruthenium_block", () -> new Block(BlockBehaviour.Properties.of().strength(4.5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RUTHENIUM_BLOCK = registerBlock("ruthenium_block", () -> new Block(BlockBehaviour.Properties.of().strength(4.52f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RAW_RHODIUM_BLOCK = registerBlock("raw_rhodium_block", () -> new Block(BlockBehaviour.Properties.of().strength(4.55f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RHODIUM_BLOCK = registerBlock("rhodium_block", () -> new Block(BlockBehaviour.Properties.of().strength(4.57f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RAW_PALLADIUM_BLOCK = registerBlock("raw_palladium_block", () -> new Block(BlockBehaviour.Properties.of().strength(4.59f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> PALLADIUM_BLOCK = registerBlock("palladium_block", () -> new Block(BlockBehaviour.Properties.of().strength(4.6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RAW_SILVER_BLOCK = registerBlock("raw_silver_block", () -> new Block(BlockBehaviour.Properties.of().strength(4.7f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> SILVER_BLOCK = registerBlock("silver_block", () -> new Block(BlockBehaviour.Properties.of().strength(4.725f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RAW_CADMIUM_BLOCK = registerBlock("raw_cadmium_block", () -> new Block(BlockBehaviour.Properties.of().strength(4.75725f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> CADMIUM_BLOCK = registerBlock("cadmium_block", () -> new Block(BlockBehaviour.Properties.of().strength(4.8f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> INDIUM_BLOCK = registerBlock("indium_block", () -> new Block(BlockBehaviour.Properties.of().strength(4.95f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> TIN_BLOCK = registerBlock("tin_block", () -> new Block(BlockBehaviour.Properties.of().strength(4.951f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> ANTIMONY_BLOCK = registerBlock("antimony_block", () -> new Block(BlockBehaviour.Properties.of().strength(4.96f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> TELLURIUM_BLOCK = registerBlock("tellurium_block", () -> new Block(BlockBehaviour.Properties.of().strength(4.99f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> IODINE_BLOCK = registerBlock("iodine_block", () -> new Block(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> XENON_BLOCK = registerBlock("xenon_block", () -> new Block(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> CAESIUM_BLOCK = registerBlock("caesium_block", () -> new Block(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> BARIUM_BLOCK = registerBlock("barium_block", () -> new Block(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> LANTHANUM_BLOCK = registerBlock("lanthanum_block", () -> new Block(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> CERIUM_BLOCK = registerBlock("cerium_block", () -> new Block(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> PRASEODYMIUM_BLOCK = registerBlock("praseodymium_block", () -> new Block(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> NEODYMIUM_BLOCK = registerBlock("neodymium_block", () -> new Block(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> PROMETHIUM_BLOCK = registerBlock("promethium_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> SAMARIUM_BLOCK = registerBlock("samarium_block", () -> new Block(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> EUROPIUM_BLOCK = registerBlock("europium_block", () -> new Block(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> GADOLINIUM_BLOCK = registerBlock("gadolinium_block", () -> new Block(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> TERBIUM_BLOCK = registerBlock("terbium_block", () -> new Block(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> DYSPROSIUM_BLOCK = registerBlock("dysprosium_block", () -> new Block(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> HOLMIUM_BLOCK = registerBlock("holmium_block", () -> new Block(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> ERBIUM_BLOCK = registerBlock("erbium_block", () -> new Block(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> THULIUM_BLOCK = registerBlock("thulium_block", () -> new Block(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> YTTERBIUM_BLOCK = registerBlock("ytterbium_block", () -> new Block(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> LUTETIUM_BLOCK = registerBlock("lutetium_block", () -> new Block(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RAW_HAFNIUM_BLOCK = registerBlock("raw_hafnium_block", () -> new Block(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> HAFNIUM_BLOCK = registerBlock("hafnium_block", () -> new Block(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RAW_TANTALUM_BLOCK = registerBlock("raw_tantalum_block", () -> new Block(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> TANTALUM_BLOCK = registerBlock("tantalum_block", () -> new Block(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RAW_TUNGSTEN_BLOCK = registerBlock("raw_tungsten_block", () -> new Block(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> TUNGSTEN_BLOCK = registerBlock("tungsten_block", () -> new Block(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RAW_RHENIUM_BLOCK = registerBlock("raw_rhenium_block", () -> new Block(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RHENIUM_BLOCK = registerBlock("rhenium_block", () -> new Block(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RAW_OSMIUM_BLOCK = registerBlock("raw_osmium_block", () -> new Block(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> OSMIUM_BLOCK = registerBlock("osmium_block", () -> new Block(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RAW_IRIDIUM_BLOCK = registerBlock("raw_iridium_block", () -> new Block(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> IRIDIUM_BLOCK = registerBlock("iridium_block", () -> new Block(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> PLATINUM_BLOCK = registerBlock("platinum_block", () -> new Block(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> THALLIUM_BLOCK = registerBlock("thallium_block", () -> new Block(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> LEAD_BLOCK = registerBlock("lead_block", () -> new Block(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> BISMUTH_BLOCK = registerBlock("bismuth_block", () -> new Block(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> POLONIUM_BLOCK = registerBlock("polonium_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(5f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> ASTATINE_BLOCK = registerBlock("astatine_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RADON_BLOCK = registerBlock("radon_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> FRANCIUM_BLOCK = registerBlock("francium_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RADIUM_BLOCK = registerBlock("radium_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> ACTINIUM_BLOCK = registerBlock("actinium_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> THORIUM_BLOCK = registerBlock("thorium_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> PROTACTINIUM_BLOCK = registerBlock("protactinium_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> URANIUM_BLOCK = registerBlock("uranium_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> NEPTUNIUM_BLOCK = registerBlock("neptunium_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> PLUTONIUM_BLOCK = registerBlock("plutonium_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> AMERICIUM_BLOCK = registerBlock("americium_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> CURIUM_BLOCK = registerBlock("curium_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> BERKELIUM_BLOCK = registerBlock("berkelium_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> CALIFORNIUM_BLOCK = registerBlock("californium_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> EINSTEINIUM_BLOCK = registerBlock("einsteinium_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> FERMIUM_BLOCK = registerBlock("fermium_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> MENDELEVIUM_BLOCK = registerBlock("mendelevium_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> NOBELIUM_BLOCK = registerBlock("nobelium_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> LAWRENCIUM_BLOCK = registerBlock("lawrencium_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> RUTHERFORDIUM_BLOCK = registerBlock("rutherfordium_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> DUBNIUM_BLOCK = registerBlock("dubnium_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> SEABORGIUM_BLOCK = registerBlock("seaborgium_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> BOHRIUM_BLOCK = registerBlock("bohrium_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> HASSIUM_BLOCK = registerBlock("hassium_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> MEITNERIUM_BLOCK = registerBlock("meitnerium_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> DARMSTADTIUM_BLOCK = registerBlock("darmstadtium_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> ROENTGENIUM_BLOCK = registerBlock("roentgenium_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> COPERNICIUM_BLOCK = registerBlock("copernicium_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> NIHONIUM_BLOCK = registerBlock("nihonium_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> FLEROVIUM_BLOCK = registerBlock("flerovium_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> MOSCOVIUM_BLOCK = registerBlock("moscovium_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> LIVERMORIUM_BLOCK = registerBlock("livermorium_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> TENNESSINE_BLOCK = registerBlock("tennessine_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    public static final DeferredBlock<Block> OGANESSON_BLOCK = registerBlock("oganesson_block", () -> new SuperRadioactiveBlock(BlockBehaviour.Properties.of().strength(6f).requiresCorrectToolForDrops()));
    private static <T extends Block> DeferredBlock<T> registerBlock(String name, Supplier<T> block) {
        DeferredBlock<T> toReturn = BLOCKS.register(name, block);
        registerBlockItem(name, toReturn);
        return toReturn;
    }
    private static <T extends Block> void registerBlockItem(String name, DeferredBlock<T> block) {
        ModItems.ITEMS.register(name, () -> new BlockItem(block.get(), new Item.Properties()));
    }
    public static void register(IEventBus eventBus) {
        BLOCKS.register(eventBus);
    }
}
