package net.js.jsmenu.item;

import net.js.jsmenu.JSMenu;
import net.minecraft.world.item.Item;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredRegister;

public class ModItems {
    public static final DeferredRegister.Items ITEMS = DeferredRegister.createItems(JSMenu.MOD_ID);

    public static final DeferredItem<Item> HYDROGEN = ITEMS.register("hydrogen", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> HELIUM = ITEMS.register("helium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> LITHIUM = ITEMS.register("lithium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> BERYLLIUM = ITEMS.register("beryllium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> BORON = ITEMS.register("boron", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> CARBON = ITEMS.register("carbon", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> NITROGEN = ITEMS.register("nitrogen", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> OXYGEN = ITEMS.register("oxygen", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> FLUORINE = ITEMS.register("fluorine", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> NEON = ITEMS.register("neon", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> SODIUM = ITEMS.register("sodium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> MAGNESIUM = ITEMS.register("magnesium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> ALUMINUM = ITEMS.register("aluminum", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> SILICON = ITEMS.register("silicon", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> PHOSPHORUS = ITEMS.register("phosphorus", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> SULFUR = ITEMS.register("sulfur", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> CHLORINE = ITEMS.register("chlorine", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> ARGON = ITEMS.register("argon", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> POTASSIUM = ITEMS.register("potassium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> CALCIUM = ITEMS.register("calcium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> RAW_SCANDIUM = ITEMS.register("raw_scandium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> SCANDIUM_INGOT = ITEMS.register("scandium_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> RAW_TITANIUM = ITEMS.register("raw_titanium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> TITANIUM_INGOT = ITEMS.register("titanium_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> RAW_VANADIUM = ITEMS.register("raw_vanadium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> VANADIUM_INGOT = ITEMS.register("vanadium_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> RAW_CHROMIUM = ITEMS.register("raw_chromium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> CHROMIUM_INGOT = ITEMS.register("chromium_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> RAW_MANGANESE = ITEMS.register("raw_manganese", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> MANGANESE_INGOT = ITEMS.register("manganese_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> RAW_COBALT = ITEMS.register("raw_cobalt", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> COBALT_INGOT = ITEMS.register("cobalt_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> RAW_NICKEL = ITEMS.register("raw_nickel", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> NICKEL_INGOT = ITEMS.register("nickel_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> RAW_ZINC = ITEMS.register("raw_zinc", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> ZINC_INGOT = ITEMS.register("zinc_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> GALLIUM = ITEMS.register("gallium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> GERMANIUM = ITEMS.register("germanium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> ARSENIC = ITEMS.register("arsenic", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> SELENIUM = ITEMS.register("selenium", () -> new Item(new Item.Properties()));

    public static final DeferredItem<Item> KRYPTON = ITEMS.register("krypton", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> RUBIDIUM = ITEMS.register("rubidium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> STRONTIUM = ITEMS.register("strontium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> RAW_YTTRIUM = ITEMS.register("raw_yttrium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> YTTRIUM_INGOT = ITEMS.register("yttrium_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> RAW_ZIRCONIUM = ITEMS.register("raw_zirconium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> ZIRCONIUM_INGOT = ITEMS.register("zirconium_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> RAW_NIOBIUM = ITEMS.register("raw_niobium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> NIOBIUM_INGOT = ITEMS.register("niobium_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> RAW_MOLYBDENUM = ITEMS.register("raw_molybdenum", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> MOLYBDENUM_INGOT = ITEMS.register("molybdenum_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> TECHNETIUM = ITEMS.register("technetium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> RAW_RUTHENIUM = ITEMS.register("raw_ruthenium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> RUTHENIUM_INGOT = ITEMS.register("ruthenium_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> RAW_RHODIUM = ITEMS.register("raw_rhodium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> RHODIUM_INGOT = ITEMS.register("rhodium_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> RAW_PALLADIUM = ITEMS.register("raw_palladium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> PALLADIUM_INGOT = ITEMS.register("palladium_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> RAW_SILVER = ITEMS.register("raw_silver", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> SILVER_INGOT = ITEMS.register("silver_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> RAW_CADMIUM = ITEMS.register("raw_cadmium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> CADMIUM_INGOT = ITEMS.register("cadmium_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> INDIUM = ITEMS.register("indium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> TIN = ITEMS.register("tin", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> ANTIMONY = ITEMS.register("antimony", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> TELLURIUM = ITEMS.register("tellurium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> IODINE = ITEMS.register("iodine", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> XENON = ITEMS.register("xenon", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> CAESIUM = ITEMS.register("caesium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> BARIUM = ITEMS.register("barium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> LANTHANUM = ITEMS.register("lanthanum", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> CERIUM = ITEMS.register("cerium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> PRASEODYMIUM = ITEMS.register("praseodymium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> NEODYMIUM = ITEMS.register("neodymium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> PROMETHIUM = ITEMS.register("promethium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> SAMARIUM = ITEMS.register("samarium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> EUROPIUM = ITEMS.register("europium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> GADOLINIUM = ITEMS.register("gadolinium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> TERBIUM = ITEMS.register("terbium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> DYSPROSIUM = ITEMS.register("dysprosium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> HOLMIUM = ITEMS.register("holmium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> ERBIUM = ITEMS.register("erbium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> THULIUM = ITEMS.register("thulium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> YTTERBIUM = ITEMS.register("ytterbium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> LUTETIUM = ITEMS.register("lutetium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> RAW_HAFNIUM = ITEMS.register("raw_hafnium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> HAFNIUM_INGOT = ITEMS.register("hafnium_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> RAW_TANTALUM = ITEMS.register("raw_tantalum", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> TANTALUM_INGOT = ITEMS.register("tantalum_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> RAW_TUNGSTEN = ITEMS.register("raw_tungsten", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> TUNGSTEN_INGOT = ITEMS.register("tungsten_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> RAW_RHENIUM = ITEMS.register("raw_rhenium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> RHENIUM_INGOT = ITEMS.register("rhenium_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> RAW_OSMIUM = ITEMS.register("raw_osmium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> OSMIUM_INGOT = ITEMS.register("osmium_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> RAW_IRIDIUM = ITEMS.register("raw_iridium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> IRIDIUM_INGOT = ITEMS.register("iridium_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> PLATINUM = ITEMS.register("platinum", () -> new Item(new Item.Properties()));

    public static final DeferredItem<Item> THALLIUM = ITEMS.register("thallium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> LEAD = ITEMS.register("lead", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> BISMUTH = ITEMS.register("bismuth", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> POLONIUM = ITEMS.register("polonium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> ASTATINE = ITEMS.register("astatine", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> RADON = ITEMS.register("radon", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> FRANCIUM = ITEMS.register("francium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> RADIUM = ITEMS.register("radium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> ACTINIUM = ITEMS.register("actinium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> THORIUM = ITEMS.register("thorium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> PROTACTINIUM = ITEMS.register("protactinium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> URANIUM = ITEMS.register("uranium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> NEPTUNIUM = ITEMS.register("neptunium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> PLUTONIUM = ITEMS.register("plutonium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> AMERICIUM = ITEMS.register("americium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> CURIUM = ITEMS.register("curium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> BERKELIUM = ITEMS.register("berkelium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> CALIFORNIUM = ITEMS.register("californium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> EINSTEINIUM = ITEMS.register("einsteinium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> FERMIUM = ITEMS.register("fermium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> MENDELEVIUM = ITEMS.register("mendelevium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> NOBELIUM = ITEMS.register("nobelium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> LAWRENCIUM = ITEMS.register("lawrencium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> RUTHERFORDIUM = ITEMS.register("rutherfordium_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> DUBNIUM = ITEMS.register("dubnium_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> SEABORGIUM = ITEMS.register("seaborgium_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> BOHRIUM = ITEMS.register("bohrium_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> HASSIUM = ITEMS.register("hassium_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> MEITNERIUM = ITEMS.register("meitnerium_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> DARMSTADTIUM = ITEMS.register("darmstadtium_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> ROENTGENIUM = ITEMS.register("roentgenium_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> COPERNICIUM = ITEMS.register("copernicium_ingot", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> NIHONIUM = ITEMS.register("nihonium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> FLEROVIUM = ITEMS.register("flerovium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> MOSCOVIUM = ITEMS.register("moscovium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> LIVERMORIUM = ITEMS.register("livermorium", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> TENNESSINE = ITEMS.register("tennessine", () -> new Item(new Item.Properties()));
    public static final DeferredItem<Item> OGANESSON = ITEMS.register("oganesson", () -> new Item(new Item.Properties()));

    public static void register(IEventBus eventBus) {
        ITEMS.register(eventBus);
    }
}
