package net.js.jsmenu.datagen;

import net.js.jsmenu.block.ModBlocks;
import net.js.jsmenu.item.ModItems;
import net.minecraft.core.Holder;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.registries.Registries;
import net.minecraft.data.loot.BlockLootSubProvider;
import net.minecraft.world.flag.FeatureFlags;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.enchantment.Enchantment;
import net.minecraft.world.item.enchantment.Enchantments;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.storage.loot.LootTable;
import net.minecraft.world.level.storage.loot.entries.LootItem;
import net.minecraft.world.level.storage.loot.functions.ApplyBonusCount;
import net.minecraft.world.level.storage.loot.functions.SetItemCountFunction;
import net.minecraft.world.level.storage.loot.providers.number.UniformGenerator;

import java.util.Set;

public class ModBlockLootTableProvider extends BlockLootSubProvider {
    protected ModBlockLootTableProvider(HolderLookup.Provider registries) {
        super(Set.of(), FeatureFlags.REGISTRY.allFlags(), registries);
    }

    @Override
    protected void generate() {
        dropSelf(ModBlocks.HYDROGEN_BLOCK.get());
        dropSelf(ModBlocks.HELIUM_BLOCK.get());
        dropSelf(ModBlocks.LITHIUM_BLOCK.get());
        dropSelf(ModBlocks.BERYLLIUM_BLOCK.get());
        dropSelf(ModBlocks.BORON_BLOCK.get());
        dropSelf(ModBlocks.CARBON_BLOCK.get());
        dropSelf(ModBlocks.NITROGEN_BLOCK.get());
        dropSelf(ModBlocks.OXYGEN_BLOCK.get());
        dropSelf(ModBlocks.FLUORINE_BLOCK.get());
        dropSelf(ModBlocks.NEON_BLOCK.get());
        dropSelf(ModBlocks.SODIUM_BLOCK.get());
        dropSelf(ModBlocks.MAGNESIUM_BLOCK.get());
        dropSelf(ModBlocks.ALUMINUM_BLOCK.get());
        dropSelf(ModBlocks.SILICON_BLOCK.get());
        dropSelf(ModBlocks.PHOSPHORUS_BLOCK.get());
        dropSelf(ModBlocks.SULFUR_BLOCK.get());
        dropSelf(ModBlocks.CHLORINE_BLOCK.get());
        dropSelf(ModBlocks.ARGON_BLOCK.get());
        dropSelf(ModBlocks.POTASSIUM_BLOCK.get());
        dropSelf(ModBlocks.CALCIUM_BLOCK.get());
        dropSelf(ModBlocks.RAW_SCANDIUM_BLOCK.get());
        dropSelf(ModBlocks.SCANDIUM_BLOCK.get());
        dropSelf(ModBlocks.RAW_TITANIUM_BLOCK.get());
        dropSelf(ModBlocks.TITANIUM_BLOCK.get());
        dropSelf(ModBlocks.RAW_VANADIUM_BLOCK.get());
        dropSelf(ModBlocks.VANADIUM_BLOCK.get());
        dropSelf(ModBlocks.RAW_CHROMIUM_BLOCK.get());
        dropSelf(ModBlocks.CHROMIUM_BLOCK.get());
        dropSelf(ModBlocks.RAW_MANGANESE_BLOCK.get());
        dropSelf(ModBlocks.MANGANESE_BLOCK.get());
        dropSelf(ModBlocks.RAW_COBALT_BLOCK.get());
        dropSelf(ModBlocks.COBALT_BLOCK.get());
        dropSelf(ModBlocks.RAW_NICKEL_BLOCK.get());
        dropSelf(ModBlocks.NICKEL_BLOCK.get());
        dropSelf(ModBlocks.RAW_ZINC_BLOCK.get());
        dropSelf(ModBlocks.ZINC_BLOCK.get());
        dropSelf(ModBlocks.GALLIUM_BLOCK.get());
        dropSelf(ModBlocks.GERMANIUM_BLOCK.get());
        dropSelf(ModBlocks.ARSENIC_BLOCK.get());
        dropSelf(ModBlocks.SELENIUM_BLOCK.get());
        dropSelf(ModBlocks.KRYPTON_BLOCK.get());
        dropSelf(ModBlocks.RUBIDIUM_BLOCK.get());
        dropSelf(ModBlocks.STRONTIUM_BLOCK.get());
        dropSelf(ModBlocks.RAW_YTTRIUM_BLOCK.get());
        dropSelf(ModBlocks.YTTRIUM_BLOCK.get());
        dropSelf(ModBlocks.RAW_ZIRCONIUM_BLOCK.get());
        dropSelf(ModBlocks.ZIRCONIUM_BLOCK.get());
        dropSelf(ModBlocks.RAW_NIOBIUM_BLOCK.get());
        dropSelf(ModBlocks.NIOBIUM_BLOCK.get());
        dropSelf(ModBlocks.RAW_MOLYBDENUM_BLOCK.get());
        dropSelf(ModBlocks.MOLYBDENUM_BLOCK.get());
        dropSelf(ModBlocks.TECHNETIUM_BLOCK.get());
        dropSelf(ModBlocks.RAW_RUTHENIUM_BLOCK.get());
        dropSelf(ModBlocks.RUTHENIUM_BLOCK.get());
        dropSelf(ModBlocks.RAW_RHODIUM_BLOCK.get());
        dropSelf(ModBlocks.RHODIUM_BLOCK.get());
        dropSelf(ModBlocks.RAW_PALLADIUM_BLOCK.get());
        dropSelf(ModBlocks.PALLADIUM_BLOCK.get());
        dropSelf(ModBlocks.RAW_SILVER_BLOCK.get());
        dropSelf(ModBlocks.SILVER_BLOCK.get());
        dropSelf(ModBlocks.RAW_CADMIUM_BLOCK.get());
        dropSelf(ModBlocks.CADMIUM_BLOCK.get());
        dropSelf(ModBlocks.INDIUM_BLOCK.get());
        dropSelf(ModBlocks.TIN_BLOCK.get());
        dropSelf(ModBlocks.ANTIMONY_BLOCK.get());
        dropSelf(ModBlocks.TELLURIUM_BLOCK.get());
        dropSelf(ModBlocks.IODINE_BLOCK.get());
        dropSelf(ModBlocks.XENON_BLOCK.get());
        dropSelf(ModBlocks.CAESIUM_BLOCK.get());
        dropSelf(ModBlocks.BARIUM_BLOCK.get());
        dropSelf(ModBlocks.LANTHANUM_BLOCK.get());
        dropSelf(ModBlocks.CERIUM_BLOCK.get());
        dropSelf(ModBlocks.PRASEODYMIUM_BLOCK.get());
        dropSelf(ModBlocks.NEODYMIUM_BLOCK.get());
        dropSelf(ModBlocks.PROMETHIUM_BLOCK.get());
        dropSelf(ModBlocks.SAMARIUM_BLOCK.get());
        dropSelf(ModBlocks.EUROPIUM_BLOCK.get());
        dropSelf(ModBlocks.GADOLINIUM_BLOCK.get());
        dropSelf(ModBlocks.TERBIUM_BLOCK.get());
        dropSelf(ModBlocks.DYSPROSIUM_BLOCK.get());
        dropSelf(ModBlocks.HOLMIUM_BLOCK.get());
        dropSelf(ModBlocks.ERBIUM_BLOCK.get());
        dropSelf(ModBlocks.THULIUM_BLOCK.get());
        dropSelf(ModBlocks.YTTERBIUM_BLOCK.get());
        dropSelf(ModBlocks.LUTETIUM_BLOCK.get());
        dropSelf(ModBlocks.RAW_HAFNIUM_BLOCK.get());
        dropSelf(ModBlocks.HAFNIUM_BLOCK.get());
        dropSelf(ModBlocks.RAW_TANTALUM_BLOCK.get());
        dropSelf(ModBlocks.TANTALUM_BLOCK.get());
        dropSelf(ModBlocks.RAW_TUNGSTEN_BLOCK.get());
        dropSelf(ModBlocks.TUNGSTEN_BLOCK.get());
        dropSelf(ModBlocks.RAW_RHENIUM_BLOCK.get());
        dropSelf(ModBlocks.RHENIUM_BLOCK.get());
        dropSelf(ModBlocks.RAW_OSMIUM_BLOCK.get());
        dropSelf(ModBlocks.OSMIUM_BLOCK.get());
        dropSelf(ModBlocks.RAW_IRIDIUM_BLOCK.get());
        dropSelf(ModBlocks.IRIDIUM_BLOCK.get());
        dropSelf(ModBlocks.PLATINUM_BLOCK.get());
        dropSelf(ModBlocks.THALLIUM_BLOCK.get());
        dropSelf(ModBlocks.LEAD_BLOCK.get());
        dropSelf(ModBlocks.BISMUTH_BLOCK.get());
        dropSelf(ModBlocks.POLONIUM_BLOCK.get());
        dropSelf(ModBlocks.ASTATINE_BLOCK.get());
        dropSelf(ModBlocks.RADON_BLOCK.get());
        dropSelf(ModBlocks.FRANCIUM_BLOCK.get());
        dropSelf(ModBlocks.RADIUM_BLOCK.get());
        dropSelf(ModBlocks.ACTINIUM_BLOCK.get());
        dropSelf(ModBlocks.THORIUM_BLOCK.get());
        dropSelf(ModBlocks.PROTACTINIUM_BLOCK.get());
        dropSelf(ModBlocks.URANIUM_BLOCK.get());
        dropSelf(ModBlocks.NEPTUNIUM_BLOCK.get());
        dropSelf(ModBlocks.PLUTONIUM_BLOCK.get());
        dropSelf(ModBlocks.AMERICIUM_BLOCK.get());
        dropSelf(ModBlocks.CURIUM_BLOCK.get());
        dropSelf(ModBlocks.BERKELIUM_BLOCK.get());
        dropSelf(ModBlocks.CALIFORNIUM_BLOCK.get());
        dropSelf(ModBlocks.EINSTEINIUM_BLOCK.get());
        dropSelf(ModBlocks.FERMIUM_BLOCK.get());
        dropSelf(ModBlocks.MENDELEVIUM_BLOCK.get());
        dropSelf(ModBlocks.NOBELIUM_BLOCK.get());
        dropSelf(ModBlocks.LAWRENCIUM_BLOCK.get());
        dropSelf(ModBlocks.RUTHERFORDIUM_BLOCK.get());
        dropSelf(ModBlocks.DUBNIUM_BLOCK.get());
        dropSelf(ModBlocks.SEABORGIUM_BLOCK.get());
        dropSelf(ModBlocks.BOHRIUM_BLOCK.get());
        dropSelf(ModBlocks.HASSIUM_BLOCK.get());
        dropSelf(ModBlocks.MEITNERIUM_BLOCK.get());
        dropSelf(ModBlocks.DARMSTADTIUM_BLOCK.get());
        dropSelf(ModBlocks.ROENTGENIUM_BLOCK.get());
        dropSelf(ModBlocks.COPERNICIUM_BLOCK.get());
        dropSelf(ModBlocks.NIHONIUM_BLOCK.get());
        dropSelf(ModBlocks.FLEROVIUM_BLOCK.get());
        dropSelf(ModBlocks.MOSCOVIUM_BLOCK.get());
        dropSelf(ModBlocks.LIVERMORIUM_BLOCK.get());
        dropSelf(ModBlocks.TENNESSINE_BLOCK.get());
        dropSelf(ModBlocks.OGANESSON_BLOCK.get());

        add(ModBlocks.HYDROGEN_ORE.get(), block -> createOreDrop(ModBlocks.HYDROGEN_ORE.get(), ModItems.HYDROGEN.get()));
        add(ModBlocks.LITHIUM_ORE.get(), block -> createOreDrop(ModBlocks.LITHIUM_ORE.get(), ModItems.LITHIUM.get()));
        add(ModBlocks.BERYLLIUM_ORE.get(), block -> createOreDrop(ModBlocks.BERYLLIUM_ORE.get(), ModItems.BERYLLIUM.get()));
        add(ModBlocks.BORON_ORE.get(), block -> createOreDrop(ModBlocks.BORON_ORE.get(), ModItems.BORON.get()));
        add(ModBlocks.CARBON_ORE.get(), block -> createOreDrop(ModBlocks.CARBON_ORE.get(), ModItems.CARBON.get()));
        add(ModBlocks.NITROGEN_ORE.get(), block -> createOreDrop(ModBlocks.NITROGEN_ORE.get(), ModItems.NITROGEN.get()));
        add(ModBlocks.OXYGEN_ORE.get(), block -> createOreDrop(ModBlocks.OXYGEN_ORE.get(), ModItems.OXYGEN.get()));
        add(ModBlocks.FLUORINE_ORE.get(), block -> createOreDrop(ModBlocks.FLUORINE_ORE.get(), ModItems.FLUORINE.get()));
        add(ModBlocks.NEON_ORE.get(), block -> createOreDrop(ModBlocks.NEON_ORE.get(), ModItems.NEON.get()));
        add(ModBlocks.SODIUM_ORE.get(), block -> createOreDrop(ModBlocks.SODIUM_ORE.get(), ModItems.SODIUM.get()));
        add(ModBlocks.MAGNESIUM_ORE.get(), block -> createOreDrop(ModBlocks.MAGNESIUM_ORE.get(), ModItems.MAGNESIUM.get()));
        add(ModBlocks.ALUMINUM_ORE.get(), block -> createOreDrop(ModBlocks.ALUMINUM_ORE.get(), ModItems.ALUMINUM.get()));
        add(ModBlocks.SILICON_ORE.get(), block -> createOreDrop(ModBlocks.SILICON_ORE.get(), ModItems.SILICON.get()));
        add(ModBlocks.PHOSPHORUS_ORE.get(), block -> createOreDrop(ModBlocks.PHOSPHORUS_ORE.get(), ModItems.PHOSPHORUS.get()));
        add(ModBlocks.SULFUR_ORE.get(), block -> createOreDrop(ModBlocks.SULFUR_ORE.get(), ModItems.SULFUR.get()));
        add(ModBlocks.CHLORINE_ORE.get(), block -> createOreDrop(ModBlocks.CHLORINE_ORE.get(), ModItems.CHLORINE.get()));
        add(ModBlocks.ARGON_ORE.get(), block -> createOreDrop(ModBlocks.ARGON_ORE.get(), ModItems.ARGON.get()));
        add(ModBlocks.POTASSIUM_ORE.get(), block -> createOreDrop(ModBlocks.POTASSIUM_ORE.get(), ModItems.POTASSIUM.get()));
        add(ModBlocks.CALCIUM_ORE.get(), block -> createOreDrop(ModBlocks.CALCIUM_ORE.get(), ModItems.CALCIUM.get()));
        add(ModBlocks.SCANDIUM_ORE.get(), block -> createOreDrop(ModBlocks.SCANDIUM_ORE.get(), ModItems.RAW_SCANDIUM.get()));
        add(ModBlocks.TITANIUM_ORE.get(), block -> createOreDrop(ModBlocks.TITANIUM_ORE.get(), ModItems.RAW_TITANIUM.get()));
        add(ModBlocks.VANADIUM_ORE.get(), block -> createOreDrop(ModBlocks.VANADIUM_ORE.get(), ModItems.RAW_VANADIUM.get()));
        add(ModBlocks.CHROMIUM_ORE.get(), block -> createOreDrop(ModBlocks.CHROMIUM_ORE.get(), ModItems.RAW_CHROMIUM.get()));
        add(ModBlocks.MANGANESE_ORE.get(), block -> createOreDrop(ModBlocks.MANGANESE_ORE.get(), ModItems.RAW_MANGANESE.get()));
        add(ModBlocks.COBALT_ORE.get(), block -> createOreDrop(ModBlocks.COBALT_ORE.get(), ModItems.RAW_COBALT.get()));
        add(ModBlocks.NICKEL_ORE.get(), block -> createOreDrop(ModBlocks.NICKEL_ORE.get(), ModItems.RAW_NICKEL.get()));
        add(ModBlocks.ZINC_ORE.get(), block -> createOreDrop(ModBlocks.ZINC_ORE.get(), ModItems.RAW_ZINC.get()));
        add(ModBlocks.GALLIUM_ORE.get(), block -> createOreDrop(ModBlocks.GALLIUM_ORE.get(), ModItems.GALLIUM.get()));
        add(ModBlocks.GERMANIUM_ORE.get(), block -> createOreDrop(ModBlocks.GERMANIUM_ORE.get(), ModItems.GERMANIUM.get()));
        add(ModBlocks.ARSENIC_ORE.get(), block -> createOreDrop(ModBlocks.ARSENIC_ORE.get(), ModItems.ARSENIC.get()));
        add(ModBlocks.SELENIUM_ORE.get(), block -> createOreDrop(ModBlocks.SELENIUM_ORE.get(), ModItems.SELENIUM.get()));
        add(ModBlocks.KRYPTON_ORE.get(), block -> createOreDrop(ModBlocks.KRYPTON_ORE.get(), ModItems.KRYPTON.get()));
        add(ModBlocks.RUBIDIUM_ORE.get(), block -> createOreDrop(ModBlocks.RUBIDIUM_ORE .get(), ModItems.RUBIDIUM.get()));
        add(ModBlocks.STRONTIUM_ORE.get(), block -> createOreDrop(ModBlocks.STRONTIUM_ORE.get(), ModItems.STRONTIUM.get()));
        add(ModBlocks.YTTRIUM_ORE.get(), block -> createOreDrop(ModBlocks.YTTRIUM_BLOCK.get(), ModItems.RAW_YTTRIUM.get()));
        add(ModBlocks.ZIRCONIUM_ORE.get(), block -> createOreDrop(ModBlocks.ZIRCONIUM_ORE.get(), ModItems.RAW_ZIRCONIUM.get()));
        add(ModBlocks.NIOBIUM_ORE.get(), block -> createOreDrop(ModBlocks.NIOBIUM_ORE.get(), ModItems.RAW_NIOBIUM.get()));
        add(ModBlocks.MOLYBDENUM_ORE.get(), block -> createOreDrop(ModBlocks.MOLYBDENUM_ORE.get(), ModItems.RAW_MOLYBDENUM.get()));
        add(ModBlocks.TECHNETIUM_ORE.get(), block -> createOreDrop(ModBlocks.TECHNETIUM_ORE.get(), ModItems.TECHNETIUM.get()));
        add(ModBlocks.RUTHENIUM_ORE.get(), block -> createOreDrop(ModBlocks.RUTHENIUM_ORE.get(), ModItems.RAW_RUTHENIUM.get()));
        add(ModBlocks.RHODIUM_ORE.get(), block -> createOreDrop(ModBlocks.RHODIUM_ORE.get(), ModItems.RAW_RHODIUM.get()));
        add(ModBlocks.PALLADIUM_ORE.get(), block -> createOreDrop(ModBlocks.PALLADIUM_ORE.get(), ModItems.RAW_PALLADIUM.get()));
        add(ModBlocks.SILVER_ORE.get(), block -> createOreDrop(ModBlocks.SILVER_ORE.get(), ModItems.RAW_SILVER.get()));
        add(ModBlocks.CADMIUM_ORE.get(), block -> createOreDrop(ModBlocks.CADMIUM_BLOCK.get(), ModItems.RAW_CADMIUM.get()));
        add(ModBlocks.INDIUM_ORE.get(), block -> createOreDrop(ModBlocks.INDIUM_ORE.get(), ModItems.INDIUM.get()));
        add(ModBlocks.TIN_ORE.get(), block -> createOreDrop(ModBlocks.TIN_ORE.get(), ModItems.TIN.get()));
        add(ModBlocks.ANTIMONY_ORE.get(), block -> createOreDrop(ModBlocks.ANTIMONY_ORE.get(), ModItems.ANTIMONY.get()));
        add(ModBlocks.TELLURIUM_ORE.get(), block -> createOreDrop(ModBlocks.TELLURIUM_ORE.get(), ModItems.TELLURIUM.get()));
        add(ModBlocks.IODINE_ORE.get(), block -> createOreDrop(ModBlocks.IODINE_ORE.get(), ModItems.IODINE.get()));
        add(ModBlocks.XENON_ORE.get(), block -> createOreDrop(ModBlocks.XENON_ORE.get(), ModItems.XENON.get()));
        add(ModBlocks.CAESIUM_ORE.get(), block -> createOreDrop(ModBlocks.CAESIUM_ORE.get(), ModItems.CAESIUM.get()));
        add(ModBlocks.BARIUM_ORE.get(), block -> createOreDrop(ModBlocks.BARIUM_ORE.get(), ModItems.BARIUM.get()));
        add(ModBlocks.LANTHANUM_ORE.get(), block -> createOreDrop(ModBlocks.LANTHANUM_ORE.get(), ModItems.LANTHANUM.get()));
        add(ModBlocks.CERIUM_ORE.get(), block -> createOreDrop(ModBlocks.CERIUM_ORE.get(), ModItems.CERIUM.get()));
        add(ModBlocks.PRASEODYMIUM_ORE.get(), block -> createOreDrop(ModBlocks.PRASEODYMIUM_ORE.get(), ModItems.PRASEODYMIUM.get()));
        add(ModBlocks.NEODYMIUM_ORE.get(), block -> createOreDrop(ModBlocks.NEODYMIUM_ORE.get(), ModItems.NEODYMIUM.get()));
        add(ModBlocks.PROMETHIUM_ORE.get(), block -> createOreDrop(ModBlocks.PROMETHIUM_ORE.get(), ModItems.PROMETHIUM.get()));
        add(ModBlocks.SAMARIUM_ORE.get(), block -> createOreDrop(ModBlocks.SAMARIUM_ORE.get(), ModItems.SAMARIUM.get()));
        add(ModBlocks.EUROPIUM_ORE.get(), block -> createOreDrop(ModBlocks.EUROPIUM_ORE.get(), ModItems.EUROPIUM.get()));
        add(ModBlocks.GADOLINIUM_ORE.get(), block -> createOreDrop(ModBlocks.GADOLINIUM_ORE.get(), ModItems.GADOLINIUM.get()));
        add(ModBlocks.TERBIUM_ORE.get(), block -> createOreDrop(ModBlocks.TERBIUM_ORE.get(), ModItems.TERBIUM.get()));
        add(ModBlocks.DYSPROSIUM_ORE.get(), block -> createOreDrop(ModBlocks.DYSPROSIUM_ORE.get(), ModItems.DYSPROSIUM.get()));
        add(ModBlocks.HOLMIUM_ORE.get(), block -> createOreDrop(ModBlocks.HOLMIUM_ORE.get(), ModItems.HOLMIUM.get()));
        add(ModBlocks.ERBIUM_ORE.get(), block -> createOreDrop(ModBlocks.ERBIUM_ORE.get(), ModItems.ERBIUM.get()));
        add(ModBlocks.THULIUM_ORE.get(), block -> createOreDrop(ModBlocks.THULIUM_ORE.get(), ModItems.THULIUM.get()));
        add(ModBlocks.YTTERBIUM_ORE.get(), block -> createOreDrop(ModBlocks.YTTERBIUM_ORE.get(), ModItems.YTTERBIUM.get()));
        add(ModBlocks.LUTETIUM_ORE.get(), block -> createOreDrop(ModBlocks.LUTETIUM_ORE.get(), ModItems.LUTETIUM.get()));
        add(ModBlocks.HAFNIUM_ORE.get(), block -> createOreDrop(ModBlocks.HAFNIUM_ORE.get(), ModItems.RAW_HAFNIUM.get()));
        add(ModBlocks.TANTALUM_ORE.get(), block -> createOreDrop(ModBlocks.TANTALUM_ORE.get(), ModItems.RAW_TANTALUM.get()));
        add(ModBlocks.TUNGSTEN_ORE.get(), block -> createOreDrop(ModBlocks.TUNGSTEN_ORE.get(), ModItems.RAW_TUNGSTEN.get()));
        add(ModBlocks.RHENIUM_ORE.get(), block -> createOreDrop(ModBlocks.RHENIUM_ORE.get(), ModItems.RAW_RHENIUM.get()));
        add(ModBlocks.OSMIUM_ORE.get(), block -> createOreDrop(ModBlocks.OSMIUM_ORE.get(), ModItems.RAW_OSMIUM.get()));
        add(ModBlocks.IRIDIUM_ORE.get(), block -> createOreDrop(ModBlocks.IRIDIUM_ORE.get(), ModItems.RAW_IRIDIUM.get()));
        add(ModBlocks.PLATINUM_ORE.get(), block -> createOreDrop(ModBlocks.PLATINUM_ORE.get(), ModItems.PLATINUM.get()));
        add(ModBlocks.THALLIUM_ORE.get(), block -> createOreDrop(ModBlocks.THALLIUM_ORE.get(), ModItems.THALLIUM.get()));
        add(ModBlocks.LEAD_ORE.get(), block -> createOreDrop(ModBlocks.LEAD_ORE.get(), ModItems.LEAD.get()));
        add(ModBlocks.BISMUTH_ORE.get(), block -> createOreDrop(ModBlocks.BISMUTH_ORE.get(), ModItems.BISMUTH.get()));
        add(ModBlocks.POLONIUM_ORE.get(), block -> createOreDrop(ModBlocks.POLONIUM_ORE.get(), ModItems.POLONIUM.get()));
        add(ModBlocks.ASTATINE_ORE.get(), block -> createOreDrop(ModBlocks.ASTATINE_ORE.get(), ModItems.ASTATINE.get()));
        add(ModBlocks.RADON_ORE.get(), block -> createOreDrop(ModBlocks.RADON_BLOCK.get(), ModItems.RADON.get()));
        add(ModBlocks.FRANCIUM_ORE.get(), block -> createOreDrop(ModBlocks.FRANCIUM_ORE.get(), ModItems.FRANCIUM.get()));
        add(ModBlocks.RADIUM_ORE.get(), block -> createOreDrop(ModBlocks.RADIUM_ORE.get(), ModItems.RADIUM.get()));
        add(ModBlocks.ACTINIUM_ORE.get(), block -> createOreDrop(ModBlocks.ACTINIUM_ORE.get(), ModItems.ACTINIUM.get()));
        add(ModBlocks.THORIUM_ORE.get(), block -> createOreDrop(ModBlocks.THORIUM_ORE.get(), ModItems.THORIUM.get()));
        add(ModBlocks.PROTACTINIUM_ORE.get(), block -> createOreDrop(ModBlocks.PROTACTINIUM_ORE.get(), ModItems.PROTACTINIUM.get()));
        add(ModBlocks.URANIUM_ORE.get(), block -> createOreDrop(ModBlocks.URANIUM_ORE.get(), ModItems.URANIUM.get()));
        add(ModBlocks.NEPTUNIUM_ORE.get(), block -> createOreDrop(ModBlocks.NEPTUNIUM_ORE.get(), ModItems.NEPTUNIUM.get()));
        add(ModBlocks.PLUTONIUM_ORE.get(), block -> createOreDrop(ModBlocks.PLUTONIUM_ORE.get(), ModItems.PLUTONIUM.get()));
        add(ModBlocks.AMERICIUM_ORE.get(), block -> createOreDrop(ModBlocks.AMERICIUM_ORE.get(), ModItems.AMERICIUM.get()));
        add(ModBlocks.CURIUM_ORE.get(), block -> createOreDrop(ModBlocks.CURIUM_ORE.get(), ModItems.CURIUM.get()));
        add(ModBlocks.BERKELIUM_ORE.get(), block -> createOreDrop(ModBlocks.BERKELIUM_ORE.get(), ModItems.BERKELIUM.get()));
        add(ModBlocks.CALIFORNIUM_ORE.get(), block -> createOreDrop(ModBlocks.CALIFORNIUM_ORE.get(), ModItems.CALIFORNIUM.get()));
        add(ModBlocks.EINSTEINIUM_ORE.get(), block -> createOreDrop(ModBlocks.EINSTEINIUM_ORE.get(), ModItems.EINSTEINIUM.get()));
        add(ModBlocks.FERMIUM_ORE.get(), block -> createOreDrop(ModBlocks.FERMIUM_ORE.get(), ModItems.FERMIUM.get()));
        add(ModBlocks.MENDELEVIUM_ORE.get(), block -> createOreDrop(ModBlocks.MENDELEVIUM_ORE.get(), ModItems.MENDELEVIUM.get()));
        add(ModBlocks.NOBELIUM_ORE.get(), block -> createOreDrop(ModBlocks.NOBELIUM_ORE.get(), ModItems.NOBELIUM.get()));
        add(ModBlocks.LAWRENCIUM_ORE.get(), block -> createOreDrop(ModBlocks.LAWRENCIUM_ORE.get(), ModItems.LAWRENCIUM.get()));
        add(ModBlocks.RUTHERFORDIUM_ORE.get(), block -> createOreDrop(ModBlocks.RUTHERFORDIUM_ORE.get(), ModItems.RUTHERFORDIUM.get()));
        add(ModBlocks.DUBNIUM_ORE.get(), block -> createOreDrop(ModBlocks.DUBNIUM_ORE.get(), ModItems.DUBNIUM.get()));
        add(ModBlocks.SEABORGIUM_ORE.get(), block -> createOreDrop(ModBlocks.SEABORGIUM_ORE.get(), ModItems.SEABORGIUM.get()));
        add(ModBlocks.BOHRIUM_ORE.get(), block -> createOreDrop(ModBlocks.BOHRIUM_ORE.get(), ModItems.BOHRIUM.get()));
        add(ModBlocks.HASSIUM_ORE.get(), block -> createOreDrop(ModBlocks.HASSIUM_ORE.get(), ModItems.HASSIUM.get()));
        add(ModBlocks.MEITNERIUM_ORE.get(), block -> createOreDrop(ModBlocks.MEITNERIUM_ORE.get(), ModItems.MEITNERIUM.get()));
        add(ModBlocks.DARMSTADTIUM_ORE.get(), block -> createOreDrop(ModBlocks.DARMSTADTIUM_ORE.get(), ModItems.DARMSTADTIUM.get()));
        add(ModBlocks.ROENTGENIUM_ORE.get(), block -> createOreDrop(ModBlocks.ROENTGENIUM_ORE.get(), ModItems.ROENTGENIUM.get()));
        add(ModBlocks.COPERNICIUM_ORE.get(), block -> createOreDrop(ModBlocks.COPERNICIUM_ORE.get(), ModItems.COPERNICIUM.get()));
        add(ModBlocks.NIHONIUM_ORE.get(), block -> createOreDrop(ModBlocks.NIHONIUM_ORE.get(), ModItems.NIHONIUM.get()));
        add(ModBlocks.FLEROVIUM_ORE.get(), block -> createOreDrop(ModBlocks.FLEROVIUM_ORE.get(), ModItems.FLEROVIUM.get()));
        add(ModBlocks.MOSCOVIUM_ORE.get(), block -> createOreDrop(ModBlocks.MOSCOVIUM_ORE.get(), ModItems.MOSCOVIUM.get()));
        add(ModBlocks.LIVERMORIUM_ORE.get(), block -> createOreDrop(ModBlocks.LIVERMORIUM_ORE.get(), ModItems.LIVERMORIUM.get()));
        add(ModBlocks.TENNESSINE_ORE.get(), block -> createOreDrop(ModBlocks.TENNESSINE_ORE.get(), ModItems.TENNESSINE.get()));
        add(ModBlocks.OGANESSON_ORE.get(), block -> createOreDrop(ModBlocks.OGANESSON_ORE.get(), ModItems.OGANESSON.get()));
    }

    protected LootTable.Builder createMultipleOreDrops(Block pBlock, Item item, float minDrops, float maxDrops) {
        HolderLookup.RegistryLookup<Enchantment> registryLookup = this.registries.lookupOrThrow(Registries.ENCHANTMENT);
        return this.createSilkTouchDispatchTable(pBlock,
                this.applyExplosionDecay(pBlock, LootItem.lootTableItem(item)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(minDrops, maxDrops)))
                        .apply(ApplyBonusCount.addOreBonusCount(registryLookup.getOrThrow(Enchantments.FORTUNE)))));
    }

    @Override
    protected Iterable<Block> getKnownBlocks() {
        return ModBlocks.BLOCKS.getEntries().stream().map(Holder::value)::iterator;
    }
}
